#.circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: /home/circleci/mastogetter
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # ログディレクトリの作成
      - run:
          command: |
            mkdir -p results
            mkdir -p results/eslint
      # コーディング規約検証
      - run:
          name: eslint
          when: always
          command: |
            npm run eslint:ci
      # テスト
      - run:
          name: test
          when: always
          command: |
            npm test -- --tap | npx tap-xunit > results/ava.xml
      - store_test_results:
          path: results
      - store_artifacts:
          path: results
